# Generated by Django 2.2.12 on 2021-01-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Planner', '0002_segment_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='Event_Planner.Event'),
        ),
    ]
