# Generated by Django 2.2.12 on 2021-02-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Planner', '0003_auto_20210126_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pptx',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
