# Generated by Django 2.2.12 on 2021-02-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Planner', '0004_event_pptx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pptx',
            field=models.FileField(null=True, upload_to='songs/protected'),
        ),
    ]
