# Generated by Django 2.2.12 on 2021-01-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SongManager', '0003_auto_20170919_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='SongManager.Song'),
        ),
    ]
